### ISSUE TITLE
Meshes with many blocks and few cells

### ISSUE THREAD

**Issue by LucasLangnaese** [tkeskita/swiftBlock#13]
Hello,
thank you very much for this powerful tool!
I use it for FSI simulations of blood vessels. I create conformal structure meshes for my given fluid meshes. I do this by extruding the interface mesh for the fluid to the outside. So I get meshes with a lot of blocks but a maximum of 1 - 3 cells per block.
However, as the number of blocks increases, the computing effort required for “automatic block detection” increases significantly. Is there a way to use the tool more optimal for such a purpose? (many blocks; max 1 - 3 cells per block)
Best regards Lucas
![Screenshot from 2023-10-05 11-37-47](https://github.com/tkeskita/swiftBlock/assets/123447136/31938002-70a0-4d6f-a691-1412cfacf3e8)

**Comment by tkeskita** [comment]
Hi,

yes, large number of blocks cause slowness. You can try if Numba works and helps with speed ([see the docs](https://swiftblock.readthedocs.io/en/latest/swift.html#block-method-settings)).

Alternatively, if you're just trying to create boundary layers, try to use the [Shell Extrusion method in the Unstructured Grids add-on](https://unstructured-grids.readthedocs.io/en/latest/ug.html#extrusion-of-new-cells). Please note the limitations mentioned in docs.

**Comment by tkeskita** [comment]
[Here's an example of the Shell Extrusion method in the Unstructured Grids add-on](https://www.cfd-online.com/Forums/openfoam-community-contributions/247004-boundary-layer-extrusion-tool-using-blender.html)

**Comment by LucasLangnaese** [comment]
Thank you, the Shell Extrusion method in the Unstructured Grids add-on is exactly the right tool for my problem.
