### ISSUE TITLE
No more than 3 new blocks at time (most of the times)

### ISSUE THREAD

**Issue by Lourencosm** [tkeskita/swiftBlock#14]
First of all, this add-on is amazing! Thank you so much!

Issue:
When I try to add more than 3 new blocks at a time, no block is created.

Worfkflow:
1) Start from 1 cube.
2) Extrude the faces in the same direction 3x to obtain a 1x4 structure 
-> click "build" button, get 4 blocks)
![image](https://github.com/user-attachments/assets/0ace053c-c4ed-4122-bdb1-c718375c1fcd)
3) Extrude 4 faces (in the same plane) in the same direction to obtain a 2x4 structure 
-> click "build" button, get 8 blocks)
![image](https://github.com/user-attachments/assets/8ad6bf80-53fb-48ef-bc9c-94d810706f34)

4) Extrude 4 or more faces from the same plane
![image](https://github.com/user-attachments/assets/28e46a58-78f5-409f-96ed-0bc0a3170f73)
-> click "build" button, still having 8 blocks, the last extruded blocks disappear
![image](https://github.com/user-attachments/assets/f3afb8f0-b80d-4d44-9a99-6ba2f1fc6d45)

Alternative solution:
Is there a way to merge/delete internal faces? (delete faces or dissolve doesn't work)
This way I could extrude the faces separately and merge them afterwards.

Thank you

**Comment by Lourencosm** [comment]
My fault! But it could happen to someone else too.
I was extruding using the "E" key. Everything works perfectly if you use the add-on button 'Extrude Blocks (Retain Internal Edges)'.

**Comment by danielbruno77** [comment]
One thing I noticed can happen is the generation of doubled vertices/edges/faces when extruding the block using the **swiftBlock**'s ```Extrude Blocks (Retain Internal Edges)```. The remedy for this is to **merge** the doubled vertices using the ```Mesh -> Merge -> By Distance``` tool in Edit Mode.

**Comment by Lourencosm** [comment]
This is not an issue, it is more of an advice or attention call for users.
