### ISSUE TITLE
Can't use preview

### ISSUE THREAD

**Issue by twenrut** [tkeskita/swiftBlock#3]
My current mac os version is 11.0.1. I installed swiftBlock but when I click preview it gives this error, 
<img width="895" alt="Screen Shot 2020-11-23 at 17 10 07" src="https://user-images.githubusercontent.com/62622532/99975532-6877a700-2db3-11eb-8430-1a15b1b72a76.png">
I tried to source openfoam like this, but it gives me another error which is : 
<img width="604" alt="Screen Shot 2020-11-23 at 17 12 17" src="https://user-images.githubusercontent.com/62622532/99975609-880ecf80-2db3-11eb-9430-bd01d4f5f220.png">
I'm new to UNIX, so can you give me clear explanation for what to do,  I'm trying to learn openfoam to apply jobs.

**Comment by tkeskita** [comment]
I suggest first to learn OpenFOAM and Paraview using internet resources. Only after that try swiftBlock if you have a special need for it.
