### ISSUE TITLE
Error at preview for projected naca profile

### ISSUE THREAD

**Issue by j2l** [tkeskita/swiftBlock#7]
Hello,
I'm trying some validation using swiftBlock, like https://www.cfd-online.com/Forums/openfoam-solving/232980-validatation-naca-0012-ofv2006-lack-precision.html
The naca0012 at 3° is set, the cube is set like in the example.
The preview before projecting the naca profile is fine:
![image](https://user-images.githubusercontent.com/65325/123628640-9f171380-d813-11eb-8806-922525789c4f.png)
But after projection I got error:
```
Read prefs: /home/pm/.config/blender/2.93/config/userpref.blend
Registered W_Mesh
Warning: <class 'swiftBlock-master.SWIFTBLOCK_PG_BlockProperty'> registration failed, continuing..
Warning: <class 'swiftBlock-master.SWIFTBLOCK_PG_ProjectionProperty'> registration failed, continuing..
Warning: <class 'swiftBlock-master.SWIFTBLOCK_PG_EdgeGroupProperty'> registration failed, continuing..
Read blend: /media/pm/Data/Documents/blockMesh_3naca0012.blend
OpenFOAM temp directory: /tmp/tmpb1fjnf8k
running blockMesh


--> FOAM FATAL IO ERROR: 
Expected a '(' or a '{' while reading List, found on line 26 the word 'naca0012'

file: /tmp/tmpb1fjnf8k/system/blockMeshDict at line 26.

    From function char Foam::Istream::readBeginList(const char*)
    in file db/IOstreams/IOstreams/Istream.C at line 134.

FOAM exiting

Python: Traceback (most recent call last):
  File "/home/pm/.config/blender/2.93/scripts/addons/swiftBlock-master/__init__.py", line 604, in invoke
    points, faces = mesh.runMesh()
  File "/home/pm/.config/blender/2.93/scripts/addons/swiftBlock-master/blockMeshMG.py", line 216, in runMesh
    faces, bcifaces=self.getBCFaces2(internalCells)
  File "/home/pm/.config/blender/2.93/scripts/addons/swiftBlock-master/blockMeshMG.py", line 187, in getBCFaces2
    startLine, numberofLines = self.readHeader(facesFile)
  File "/home/pm/.config/blender/2.93/scripts/addons/swiftBlock-master/blockMeshMG.py", line 104, in readHeader
    with open(dicfile) as fin:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpktud3brz/constant/polyMesh/faces'

location: <unknown location>:-1
```
For this kind of domain, I also tried with a boolean difference (profile removed from domain cube) to get a hollow domain, but at building, the plugin simply ignore the profile and I get a plain parallelepipede. 
Which typology should the domain cube have for "edge to edge on Y axis" domain?
Thanks

Here's my blend file:
[blockMesh_3naca0012.blend.zip](https://github.com/tkeskita/swiftBlock/files/6725866/blockMesh_3naca0012.blend.zip)

**Comment by tkeskita** [comment]
Sorry no time now, but you can [ask for advice here](https://www.cfd-online.com/Forums/openfoam-community-contributions/100604-swiftsnap-swiftblock-guis-openfoams-meshers.html).

**Comment by j2l** [comment]
I already had: https://www.cfd-online.com/Forums/openfoam-community-contributions/100604-swiftsnap-swiftblock-guis-openfoams-meshers-15.html#post807116
:smile:

**Comment by j2l** [comment]
@tkeskita or someone, when you have time, would you please let me know how to do it?
Thank you in advance

**Comment by tkeskita** [comment]
Sorry for the long delay. I've now upgraded Swift Block to Blender LTS 3.3, and at the same time I'm going through reported issues.

The issue here is that the projection object name `3naca0012` starts with a number `3`. That makes `blockMesh` think it's about to receive 3 items, hence the error `Expected a '(' or a '{' while reading List, found on line 26 the word 'naca0012'`. If you change the object name so it starts with a letter, then it works. I will update the docs to mention this pitfall.

PS. I've been testing this NACA airfoil case with Swift Block, I'll add it as an extra example to the addon, since I think many users are interested in this kind of a more practical example. Thanks for submitting this issue!

BR,
Tuomo

**Comment by j2l** [comment]
Thank you @tkeskita
