### ISSUE TITLE
"Extrude Blocks" does not appear in version 2.93

### ISSUE THREAD

**Issue by wangsen992** [tkeskita/swiftBlock#8]
I just get started with using the add-on and it seems so good I can't believe it. But in terms of updates maybe I could contribute somehow? The operator "Extrude Blocks" does not appear in version 2.93. I tested 2.83 and it worked. Below are the screeshot for the error messages appeared while installing the add-on for 2.93. 

![image](https://user-images.githubusercontent.com/6318958/168395594-85e31e9e-b3e7-455a-8d2a-abb84def81e0.png)

**Comment by tkeskita** [comment]
Hi! Please feel free to contribute! I have currently other stuff on my table, so if you can come up with a patch that fixes this issue please send pull request. Thanks!
