### ISSUE TITLE
HOW can I save this problem

### ISSUE THREAD

**Issue by dundunplus** [tkeskita/swiftBlock#9]
Python: Traceback (most recent call last):
  File "/Users/Alex/Library/Application Support/Blender/3.4/scripts/addons/swiftBlock-master/__init__.py", line 799, in execute
    e[timel] = time.time()
TypeError: 'float' object cannot be interpreted as an integer

**Comment by tkeskita** [comment]
Hi,
currently Swift Block add-on works with Blender LTS 2.83. I will try to find time to upgrade to Blender LTS 3.3 in future.

**Comment by dundunplus** [comment]
Thank you for your time
